version: "3.8"

services:
  lendingbot:
    container_name: lendingbot
    build:
      context: .
    image: lendingbot:latest
    restart: unless-stopped
    environment:
      - LENDINGBOT_CONFIG=/config/default.cfg
      - TZ=UTC
    volumes:
      - ./default.cfg:/config/default.cfg:ro
      - ./market_data:/app/market_data
      - ./logs:/app/www
    ports:
      - "8000:8000"
